[general]
host = "0.0.0.0"
port = 5000
root = "./"
page404 = "404.html"
page50x = "50x.html"
log-level = "info"
directory-listing = false
cache-control-headers = false
index-files = "index.html"
ignore-hidden-files = true
disable-symlinks = true

[general.cors]
origins = ["*"]
methods = ["GET", "POST", "PUT", "DELETE", "HEAD", "OPTIONS"]
headers = ["*"]

[general.headers]
cache-control = "max-age=86400"

[general.headers.security]
x-frame-options = "DENY"
x-content-type-options = "nosniff"

[[advanced.headers]]
source = "**"
[advanced.headers.headers]
Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
Pragma = "no-cache"
Expires = "0"